# Generated by Django 4.1.7 on 2023-03-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StusdentId', models.AutoField(primary_key=True, serialize=False)),
                ('StudentName', models.CharField(max_length=300)),
                ('StudentLastName', models.CharField(max_length=300)),
                ('StudentAccount', models.DateField()),
            ],
        ),
    ]
